// <auto-generated />
using System;
using ArtsemiLasyi.PetsApp.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtsemiLasyi.PetsApp.DataAccess.Migrations
{
    [DbContext(typeof(PetsAppDbContext))]
    [Migration("20240811201948_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtsemiLasyi.PetsApp.DataAccess.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PetBreedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("WeightInGrams")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PetBreedId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("ArtsemiLasyi.PetsApp.DataAccess.Entities.PetBreed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PetTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PetTypeId");

                    b.ToTable("PetBreeds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0fbfad5b-d9cb-469f-a165-70867728950e"),
                            Name = "Macaw",
                            PetTypeId = new Guid("0fafad5b-d9cb-469f-a165-70867728950e")
                        },
                        new
                        {
                            Id = new Guid("0fcfad5b-d9cb-469f-a165-70867728950e"),
                            Name = "Cockatoo",
                            PetTypeId = new Guid("0fafad5b-d9cb-469f-a165-70867728950e")
                        },
                        new
                        {
                            Id = new Guid("0fdfad5b-d9cb-469f-a165-70867728950e"),
                            Name = "Caique",
                            PetTypeId = new Guid("0fafad5b-d9cb-469f-a165-70867728950e")
                        },
                        new
                        {
                            Id = new Guid("0fefad5b-d9cb-469f-a165-70867728950e"),
                            Name = "Abyssinian",
                            PetTypeId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e")
                        },
                        new
                        {
                            Id = new Guid("0fffad5b-d9cb-469f-a165-70867728950e"),
                            Name = "Bengal",
                            PetTypeId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e")
                        },
                        new
                        {
                            Id = new Guid("0faaad5b-d9cb-469f-a165-70867728950e"),
                            Name = "British Shrthair",
                            PetTypeId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e")
                        },
                        new
                        {
                            Id = new Guid("0fabad5b-d9cb-469f-a165-70867728950e"),
                            Name = "Alaskan Malamute",
                            PetTypeId = new Guid("0f9fad5b-d9cb-469f-a165-70867728950e")
                        },
                        new
                        {
                            Id = new Guid("0facad5b-d9cb-469f-a165-70867728950e"),
                            Name = "Komondor",
                            PetTypeId = new Guid("0f9fad5b-d9cb-469f-a165-70867728950e")
                        },
                        new
                        {
                            Id = new Guid("0fadad5b-d9cb-469f-a165-70867728950e"),
                            Name = "Drever",
                            PetTypeId = new Guid("0f9fad5b-d9cb-469f-a165-70867728950e")
                        });
                });

            modelBuilder.Entity("ArtsemiLasyi.PetsApp.DataAccess.Entities.PetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PetTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f9fad5b-d9cb-469f-a165-70867728950e"),
                            Name = "Dog"
                        },
                        new
                        {
                            Id = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            Name = "Cat"
                        },
                        new
                        {
                            Id = new Guid("0fafad5b-d9cb-469f-a165-70867728950e"),
                            Name = "Parrot"
                        });
                });

            modelBuilder.Entity("ArtsemiLasyi.PetsApp.DataAccess.Entities.Pet", b =>
                {
                    b.HasOne("ArtsemiLasyi.PetsApp.DataAccess.Entities.PetBreed", "PetBreed")
                        .WithMany()
                        .HasForeignKey("PetBreedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PetBreed");
                });

            modelBuilder.Entity("ArtsemiLasyi.PetsApp.DataAccess.Entities.PetBreed", b =>
                {
                    b.HasOne("ArtsemiLasyi.PetsApp.DataAccess.Entities.PetType", "PetType")
                        .WithMany()
                        .HasForeignKey("PetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PetType");
                });
#pragma warning restore 612, 618
        }
    }
}
